[project]
name = "people-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "colorlog>=6.9.0",
    "flasgger>=0.9.7.1",
    "flask>=3.1.2",
    "pydantic>=2.11.9",
    "pymongo>=4.15.2",
]
